### PR TITLE
refactor backend

### PR DESCRIPTION
**Pull request by Ledoux**
this PR is the first step to make the express-webrouter template ready:
- to be flexible by adding other express middleware plugins in the index.js
- to be listening to render specific templates page (and so do ssr)

### CODE REVIEW

**Comment by Ledoux** [comment]
@pocketjoso or @franblas 
I would need a review for this PR please

**Review by franblas — APPROVED** [review]

**Comment by franblas** [comment]
Is it compatible with the latest version of teleport.js ?

**Comment by Ledoux** [comment]
I need to make that work before https://github.com/snipsco/teleport/pull/53

**Comment by Ledoux** [comment]
@franblas tx
seems to work now, I merge that PR soon

**Pull request merged**
